#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Motor,  port1,           left_light,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           hand1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           hand2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           dt_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           dp1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           dp2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           gl_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right_light,   tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

struct command{
	short left;
	short right;
	short dw;
	short hand;
	short gl;
	short dt;
	short dp;
	bool ll;
	bool rl;
};
command Command;
short hd(short value)
{
    int temp = value;
    short back;
	if((abs(temp))<20)
	{
		back = 0;
	}else if(temp>0)
    {
        if(temp<64)
        {
            temp *= 5;temp /= 8;temp -= 12.5;
        }else{
            temp -= 64;temp *= 8;temp /= 5;temp += 27.5;
        }
    }else{
        if(temp>-64)
        {
            temp *= 5;temp /= 8;temp += 12.5;
        }else{
            temp += 64;temp *= 8;temp /= 5;temp -= 27.5;
        }
    }
    back = temp;
	return back;
}
task main()
{
	short up,turn;
	int zk_avg;
	command command;
	clearLCDLine(0);
	clearLCDLine(1);
	while(true)
	{
		up = vexRT[Ch3];
		up = hd(up);
		turn = vexRT[Ch1];
		turn = hd(turn);
		command.left= up-turn;
		command.right = up+turn;
		if(turn<0){command.ll=true;}
		else{command.ll=false;}
		if(turn>0){command.rl=true;}
		else{command.rl=false;}

		if(vexRT[Btn7U])//dt com
		{
			if(vexRT[Btn8U]){command.dt = 127;}
			else if(vexRT[Btn8D]){command.dt = -127;}
			else{command.dt = 0;}
		}else if(vexRT[Btn7D])// gl com
		{
			if(vexRT[Btn8U]){command.gl = 127;}
			else if(vexRT[Btn8D]){command.gl = -127;}
			else if(vexRT[Btn8L]){command.gl = 0;}
		}else if(vexRT[Btn7L])// hand com
		{
			if(vexRT[Btn8U]){command.hand = 127;}
			else if(vexRT[Btn8D]){command.hand = -127;}
			else{command.hand = 0;}
		}else if(vexRT[Btn7R])// dp com
		{
			if(vexRT[Btn8U]){command.dp = 127;}
			else if(vexRT[Btn8D]){command.dp = -127;}
			else{command.dp = 0;}
		}else
		{
			command.dp = 0;
			command.hand = 0;
			command.dt = 0;
		}

		//do
		zk_avg = nAvgBatteryLevel;
		displayLCDNumber(0,0,zk_avg/1000);
		displayLCDChar(0,1,'.');
		displayLCDNumber(0,2,zk_avg%1000);
		if(abs(command.left) <20)
			{motor[left]=0;}
		else{motor[left]=command.left;}
		if(abs(command.right) <20)
			{motor[right]=0;}
		else{motor[right]=command.right;}
		motor[gl_motor]=command.gl;
		motor[dt_motor]=command.dt;
		motor[dp1]=motor[dp2]=command.dp;
		motor[hand1]=motor[hand2]=command.hand;
		if(command.ll){motor[left_light]=127;}
		else{motor[left_light]=0;}
		if(command.rl){motor[right_light]=127;}
		else{motor[right_light]=0;}
	}
}
task Read()
{
	short up,turn;
	int zk_avg;
	clearLCDLine(0);
	clearLCDLine(1);
	while(true)
	{
		up = vexRT[Ch3];
		up = hd(up);
		turn = vexRT[Ch1];
		turn = hd(turn);
		Command.left= up-turn;
		Command.right = up+turn;
		if(turn<0){Command.ll=true;}
		else{Command.ll=false;}
		if(turn>0){Command.rl=true;}
		else{Command.rl=false;}

		if(vexRT[Btn7U])//dt com
		{
			if(vexRT[Btn8U]){Command.dt = 127;}
			else if(vexRT[Btn8D]){Command.dt = -127;}
			else{Command.dt = 0;}
		}else if(vexRT[Btn7D])// gl com
		{
			if(vexRT[Btn8U]){Command.gl = 127;}
			else if(vexRT[Btn8D]){Command.gl = -127;}
			else if(vexRT[Btn8L]){Command.gl = 0;}
		}else if(vexRT[Btn7L])// hand com
		{
			if(vexRT[Btn8U]){Command.hand = 127;}
			else if(vexRT[Btn8D]){Command.hand = -127;}
			else{Command.hand = 0;}
		}else if(vexRT[Btn7R])// dp com
		{
			if(vexRT[Btn8U]){Command.dp = 127;}
			else if(vexRT[Btn8D]){Command.dp = -127;}
			else{Command.dp = 0;}
		}else
		{
			Command.dp = 0;
			Command.hand = 0;
			Command.dt = 0;
		}
}
task Make()
{

}