#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  LeftCenterEncode, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LeftAroundEncode, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  RightAroundEncode, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  RightCenterEncode, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           RightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftWheel,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

struct state{
	short up;
	short turn;
	short LeftCenPal;
	short LeftAroPal;
	short RightCenPal;
	short RightAroPal;
	int LeftCenCode;
	int LeftAroCode;
	int RightCenCode;
	int RightAroCode;
	short LeftPower;
	short RightPower;
	int Range;
	int HandState;
};
struct Pid
{
	float Kp;
	float Ki;
	float Kd;
	int pValue;
	int iValue;
	int dValue;
	int LastError;
};

//global struct
state State;
Pid DriverPID;
//

void ReadDriverSensor()
{
	// return Palstance rad/s
	int StartLC,StartLA, StartRC, StartRA;
	StartLC = SensorValue[LeftCenterEncode];
	StartLA = SensorValue[LeftAroundEncode];
	StartRC = SensorValue[RightCenterEncode];
	StartRA = SensorValue[RightAroundEncode];
	wait1Msec(5);
	State.LeftCenCode = SensorValue[LeftCenterEncode];
	State.LeftAroCode = SensorValue[LeftAroundEncode];
	State.RightCenCode = SensorValue[RightCenterEncode];
	State.RightAroCode = SensorValue[RightAroundEncode];
	State.LeftCenPal = (State.LeftCenCode - StartLC) / 5 * 1000;
	State.LeftAroPal = (State.LeftAroCode - StartLC) / 5 * 1000;
	State.RightCenPal = (State.RightCenCode - StartRC) / 5 * 1000;
	State.RightAroPal = (State.RightAroCode - StartRC) / 5 * 1000;
}
task main()
{
	bLCDBacklight = true;
	float LeftPID,RightPID;
	DriverPID.Kp = 1;
	DriverPID.Ki = 1;
	DriverPID.Kd = 1;
	short v ;
			motor[LeftWheel] = 50;

	while(true)
	{
		v = State.LeftAroPal;
		ReadDriverSensor();
		displayLCDNumber(0,0,v);
		motor[LeftWheel] = 50;
		//motor[RightWheel] = RightPID;
	}
}
