#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
{
		short right_motor = vexRT[Ch2]*0.7;
		short left_motor = vexRT[Ch3]*0.7;
		bool break_EN = vexRT[Btn6U];
		if ((abs(right_motor)) <= 10)
		{
			right_motor = 0;
		}
		if(break_EN)
		{

			if(right_motor !=0)
			{
				if(motor[port4]<0)
				{
					right_motor = 15;
				}else{
				  right_motor= -15;
				}
			}

			if(left_motor !=0)
			{
				if(motor[port2]<0)
				{
					left_motor = 15;
				}else{
				  left_motor= -15;
				}
			}
		}
		motor[port2]=right_motor;
		motor[port3]=right_motor;
		motor[port4]=left_motor;
		motor[port5]=left_motor;
	}
}
