#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    HandCoder,      sensorPotentiometer)
#pragma config(Sensor, in2,    Xasic,          sensorAccelerometer)
#pragma config(Sensor, in3,    ExpanderBattery, sensorAnalog)
#pragma config(Sensor, in4,    Yasic,          sensorAccelerometer)
#pragma config(Sensor, dgtl1,  BoomLock,       sensorTouch)
#pragma config(Sensor, dgtl2,  KeyTouch,       sensorTouch)
#pragma config(Sensor, dgtl3,  HighHandTouch,  sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           GlMotor,       tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port3,           DtMotor,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           HighHandMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           HandMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BoomMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BoomMotorAnother, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LeftWheel,     tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RightWheel,    tmotorVex393_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port10,          Light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(DatalogSeries, 0, "LeftEncoder", Motors, MotorEncoder, port8, 10)
#pragma config(DatalogSeries, 1, "RightEncoder", Motors, MotorEncoder, port9, 10)
#pragma config(MotorPidSetting,  port8,  50, 9, 1000, 12, 10,  25, 80, 140)
#pragma config(MotorPidSetting,  port9,  50, 9, 1000, 12, 10,  25, 80, 140)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void FrontAuto10S()
{
	waitUntil(vexRT[Btn8U]);
	waitUntil(!vexRT[Btn8U]);
	resetMotorEncoder(LeftWheel);
	resetMotorEncoder(RightWheel);
	waitUntil(SensorValue[KeyTouch]);
	waitUntil(!SensorValue[KeyTouch]);
	clearTimer(T1);
	motor[BoomMotor] = motor[BoomMotorAnother] = 127;
	motor[HandMotor] = 50;
	waitUntil(SensorValue[BoomLock]);
	wait1Msec(500);
	motor[BoomMotor] = motor[BoomMotorAnother] = 0;
	setMotorTarget(LeftWheel, 0 ,70,false);
	setMotorTarget(RightWheel, 0,70,false);
	motor[HandMotor] = -35;
	waitUntil(getMotorTargetCompleted(LeftWheel)& getMotorTargetCompleted(RightWheel));
	motor[LeftWheel]=motor[RightWheel] = 127;
	waitUntil(getMotorEncoder(LeftWheel) > 950|getMotorEncoder(RightWheel) > 950);
	motor[LeftWheel]=motor[RightWheel] = 0;
	motor[HandMotor] = 127;
	wait1Msec(750);
	motor[LeftWheel]=motor[RightWheel] = -127;
	wait1Msec(1000);
	motor[LeftWheel]=motor[RightWheel] = 0;
}
void RearAuto5S()
{
	waitUntil(SensorValue[KeyTouch]);
	resetMotorEncoder(LeftWheel);
	resetMotorEncoder(RightWheel);
	short Code = 1100;
	setMotorTarget(LeftWheel, Code ,110,false);
	setMotorTarget(RightWheel,Code,110,false);
	motor[GlMotor] = -127;
	waitUntil(getMotorTargetCompleted(LeftWheel)& getMotorTargetCompleted(RightWheel));
}
/*
0:Red
1:Blue
*/
void RearAuto10S(bool Team)
{
	bLCDBacklight = true;
	waitUntil(SensorValue[KeyTouch]);
	clearTimer(T1);
	resetMotorEncoder(LeftWheel);
	resetMotorEncoder(RightWheel);
	short Code = 1000;
	setMotorTarget(LeftWheel, Code ,110,false);
	setMotorTarget(RightWheel,Code,110,false);
	waitUntil(getMotorTargetCompleted(LeftWheel)& getMotorTargetCompleted(RightWheel));
	resetMotorEncoder(LeftWheel);
	resetMotorEncoder(RightWheel);
	if(Team)
	{
		setMotorTarget(LeftWheel,  340  ,70,false);
		setMotorTarget(RightWheel,-340  ,70,false);
	}else{
		setMotorTarget(LeftWheel, -340  ,70,false);
		setMotorTarget(RightWheel, 340  ,70,false);
	}
	waitUntil(getMotorTargetCompleted(LeftWheel)& getMotorTargetCompleted(RightWheel));
	motor[LeftWheel]=motor[RightWheel] = 127;
	wait1Msec(1500);
	motor[LeftWheel]=motor[RightWheel] = 0;
	displayLCDNumber(0,0,time1[T1]);
}
